
spring.datasource.url=jdbc:postgresql://localhost:5432/bazunia_db


spring.datasource.username=postgres_user
spring.datasource.password=adminpostgre


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update


jwt.secret.key=cTlVMmdQNWg3RTRmQjF6TDhrWTZKM2VOMHhSY0g0c1dwVm1DN3RBMnJYYlE4eUk1b0dqRHVTOXZGNndQM2NFMQ==


server.port=8080

file.upload-dir=./vps-uploads

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gabriel.piatek.biznes@gmail.com
spring.mail.password=tvpwunxfvgailalk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true